apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      host: host.docker.internal
      port: 8123
      username: default
      defaultDatabase: otel
      defaultTable: otel_traces
      protocol: http
      tlsSkipVerify: false
      secure: false
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: latest
        durationUnit: nanoseconds
        traceIdColumn: TraceID
        spanIdColumn: SpanID
        parentSpanIdColumn: ParentSpanID
        serviceNameColumn: ServiceName
        operationNameColumn: SpanName
        startTimeColumn: Timestamp
        durationTimeColumn: Duration
        tagsColumn: SpanAttributes
        serviceTagsColumn: ResourceAttributes
        eventsPrefix: Event
    secureJsonData:
      password: clickhouse