services:
  # OpenTelemetry Collector
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml", "--set=service.telemetry.logs.level=DEBUG"]
    volumes:
      - ./config/otel/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - otel-network

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
    volumes:
      # Expose the data file:
      - ../clickhouse:/var/lib/clickhouse
      - ./config/clickhouse/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./config/clickhouse/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ../backups:/backups
    networks:
      - otel-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.50.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - otel-network

  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource,vertamedia-clickhouse-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./config/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - otel-network

volumes:
  grafana-storage:
  prometheus-data:

networks:
  otel-network:
    driver: bridge