global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - action: labeldrop
        regex: ^target_info.*

  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888'] 